### ISSUE TITLE
Cannot convert a single PNG into GIF without --features=video

### ISSUE THREAD

**Issue by jbeich** [ImageOptim/gifski#178]
When building using default features gifski errors out suggesting to export frames manually but it doesn't really work. I can't build with `--features=video` due to https://github.com/zmwangx/rust-ffmpeg/issues/63

```
$ rustc -vV
rustc 1.52.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-freebsd
release: 1.52.1
LLVM version: 12.0.0

$ curl -O https://github.com/fluidicon.png
$ cargo run -- fluidicon.png --output fluidicon.gif
    Finished dev [optimized + debuginfo] target(s) in 0.02s
     Running `target/debug/gifski fluidicon.png --output fluidicon.gif`
error: Video support is permanently disabled in this executable.

To enable video decoding you need to recompile gifski from source with:
cargo build --release --features=video
or
cargo install gifski --features=video

Alternatively, use ffmpeg command to export PNG frames, and then specify
the PNG files as input for this executable.
```

**Comment by kornelski** [comment]
Yes, indeed. This is a tool for animations, and a single frame is not an animation. gifski has no unique advantage for static images.

For single-frame PNG to GIF conversion you can use any other graphics tool that's out there, but it'd be best if you never ever used GIF for static images. Animgif still persists, because there's no equally compatible replacement. But for static images there's PNG, including [PNG8](https://pngquant.org) which is basically superior to GIF in every way, and is equally compatible.
