### ISSUE TITLE
Does gifski not support x86?

### ISSUE THREAD

**Issue by MaledongGit** [ImageOptim/gifski#189]
Hi,

Is there a gifski.dll for x86? I'm now using ScreenToGif but it doesn't work on x86 properly....:(

Ref: 
https://github.com/NickeManarin/ScreenToGif/issues/462

PS: If possible, would you plz tell me where to download the dll for x86? From which version?

**Comment by kornelski** [comment]
I don't make builds for 32-bit x86, because Intel has discontinued x64 13 years ago. At this point it's a vintage platform and I assume most remaining users of 32-bit software use it by mistake (e.g. because of installing a 32-bit OS on a 64-bit machine).

It's completely untested on 32-bit platforms, but it should work. You will have to get Rust and compile gifski yourself.

**Comment by MaledongGit** [comment]
@kornelski : Thank you for your patience, I'll fix it as a Bug for ScreenForGif :D
