### ISSUE TITLE
Is it possible to build gifski with edition: 2018

### ISSUE THREAD

**Issue by jeroen** [ImageOptim/gifski#241]
Hello! Thanks for gifski!

I maintain the bindings for the R programming language, and would like to update from 1.4.3 to 1.6.6. However many of our users are on a shared linux machines where they don't have root, and can only use the version of cargo/rust that ships with the OS:

 - Debian:stable: [rust 1.41.1](https://packages.debian.org/bullseye/rustc)
 - Debian:oldrel: [rust 1.48](https://packages.debian.org/bullseye/rustc)
 - Ubuntu:xenial: rust: 1.46

This is a problem because the minimum edition in gifski was recently bumped to 2021:

https://github.com/ImageOptim/gifski/blob/359d2ef54b5e49722585b453f765e19d1bf9ed7a/Cargo.toml#L15

So on these machines we get this build error:

```
error: failed to parse manifest at `/gifski/src/.cargo/registry/src/github.com-1ecc6299db9ec823/gifski-1.6.6/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

Sadly we need to be able to support these users. Was there anything in particular that requires edition 2021? Or is the only solution for me to downgrade gifski to 1.6.4 which still had edition 2018?

**Comment by kornelski** [comment]
gifski 1.5.1 is the most recent version that may work with Debian-packaged Rust. I do not recommend using Debian-packaged Rust at all. The latest gifski works fine on Debian if you get Rust via https://rustup.rs

I realize Debian users prefer using Debian's packages, but Debian's policies are deeply incompatible with the Rust project's policies (Rust follows Chrome's "evergreen" approach). As a result, Debian always ships Rust versions that are no longer supported by the Rust project. The Rust ecosystem has largely given up on Debian, so it's difficult to use Rust dependencies and support Debian's Rust at the same time. The situation is pretty bleak for Debian, as its v1.41 package [is not going to be able to compile over 80% of actively maintained Rust crates](https://lib.rs/stats#rustc).

Currently the code requires Rust 1.55. I've bumped it to Rust 1.56, since edition mismatch gives a better incompatibility error message than random compilation error. I could reasonably support Rust 1.54. Below that, it starts getting difficult, and I'd have to use worse code and downgrade some dependencies. It would be cumbersome to support any Rust version older than 1.51. But 1.41 is ancient by Rust's standards and it'd need special handling, like backporting changes to old gifski version or vendoring/rewriting dependencies.

**Comment by jeroen** [comment]
OK so I guess I'll ship two configurations with my bindings, and do a build-time check on the version of rust/cargo to decide if I will build the current 1.4.3 build, or the new 1.6.6.

What is the proper way to detect if rust/cargo supports edition 2021? Should I just look at `cargo --version` and try to condition on that?

**Comment by jeroen** [comment]
Ended up doing something like this:

```sh
VERSION=$(cargo --version)
if [ $? -eq 0 ]; then
  echo "Using `which cargo`"
  echo "$VERSION"

  # Check for old version of rustc (edition:2021 requires rust 1.56)
  if [ "$(uname)" = "Linux" ]; then
    VERNUM=$(echo $VERSION | cut -d' ' -f2) || true
    MAJOR=$(echo $VERNUM | cut -d'.' -f1) || true
    MINOR=$(echo $VERNUM | cut -d'.' -f2) || true
    if [ "$MAJOR" -eq "1" ] && [ "$MINOR" -lt "56" ]; then
      echo "Found old rust. Using legacy gifski 1.4.3 build."
      cp -f src/legacy/* src/myrustlib/
    fi
  fi
  exit 0
fi

```

**Comment by kornelski** [comment]
yeah, `rustc --version` or `cargo --version` is a good way to check.
