### ISSUE TITLE
please rename 1.31.1 tag to 1.13.1

### ISSUE THREAD

**Issue by landfillbaby** [ImageOptim/gifski#324]
it was presumably a typo, and it breaks automated packaging.
see https://github.com/ImageOptim/gifski/tags and https://repology.org/project/gifski/report

**Comment by kornelski** [comment]
Deleted the tag

**Comment by bevanjkay** [comment]
@kornelski Homebrew maintainer here.

Just a courtesy heads up that users who installed `gifski` between when the erroneous version `1.31.1` was released and today will be "stuck" on version `1.31.1` until the version number surpasses `1.31.1` (or they manually run `brew reinstall gifski` or `brew uninstall gifski` and `brew install gifski`) due to it not being seen as a newer version.

The only way to avoid having to wait this out, would be to jump ahead and tag the next release as `1.31.2` or `1.32.0`.

Otherwise, just keep in mind if any users ask that they can use `brew reinstall gifski` to get back on track.

---

I'm not sure how/if this may affect any other package managers.

**Comment by kornelski** [comment]
Thanks. I'll probably fast forward the version number.
