### ISSUE TITLE
Video support is permanently disabled in this executable

### ISSUE THREAD

**Issue by majkinetor** [ImageOptim/gifski#69]
Not sure why this, since you built it ? Whats the point ?

gifski 0.8.5 from releases here:

```
> .\gifski.exe .\login2.gif --output login2.optimized.gif
Error: Video support is permanently disabled in this executable.

To enable video decoding you need to recompile gifski from source with:
cargo build --release --features=video

Alternatively, use ffmpeg command to export PNG frames, and then specify
the PNG files as input for this executable.
```

So, could you make a 'video' version ?

**Comment by kornelski** [comment]
Sorry, I can't, because the video support requires installation of ffmpeg, which is a pain in the ass. If I compiled it with video, instead of this error, you'd get error about missing DLL or .so files.

It used to work with homebrew, but homebrew has upgraded to an ffmpeg version that is no longer compatible with gifski.

So there's no video support any more.

Convert video to png frames instead.
