### ISSUE TITLE
Lowest filesize when use 100 quality

### ISSUE THREAD

**Issue by olegdeezus** [ImageOptim/gifski#79]
When converting this file:
[Screen Recording 2019-04-23 at 21.09.38.mov.zip](https://github.com/ImageOptim/gifski/files/3109131/Screen.Recording.2019-04-23.at.21.09.38.mov.zip)

I receive this results:

Command | Size
---------- | ----
`gifski --fps 50 --quality 100 -W 600 -H 800 -o ~/screen.gif ~/tmp/screen*.png` | 16,6 MB
`gifski --fps 50 --quality 99 -W 600 -H 800 -o ~/screen.gif ~/tmp/screen*.png` | 23,6 MB
 `gifski --fps 50 --quality 50 -W 600 -H 800 -o ~/screen.gif ~/tmp/screen*.png` | 46,7 MB

Any thoughts, guys?

**Comment by kornelski** [comment]
That's because a low quality palette quality creates dithering, and dithering compresses worse than smooth areas that can be achieved only with a higher-quality palette.

It's a difficult trade-off, which depends on the content of the image, and it's very hard to predict how it will work out without encoding both low and high quality and comparing them.

**Comment by kornelski** [comment]
When compiled with `--features=gifsicle` it will use better compression now.
