### ISSUE TITLE
Any plans to provide a C++ API without requiring Rust to build?

### ISSUE THREAD

**Issue by mitchcurtis** [ImageOptim/gifski#91]
I would love to use this in my editor (written in C++) to export GIFs, but don't want to have Rust as a dependency. Are there any plans to provide a C++ API? Or do you know if anyone else has done this?

**Comment by kornelski** [comment]
It should be possible to add a C++ API on top of the C API.

This library is written in Rust, and I'm migrating its dependencies from C to pure Rust, so eventually I may be able to completely remove *C* as a dependency, but Rust is here to stay.

Maybe you could pre-compile this library and keep the precompiled binaries around, instead of building them from scratch each time? The static libraries produced by Rust are compatible with GCC/Clang and MSVC and can be linked directly with a C linker.

**Comment by mitchcurtis** [comment]
> It should be possible to add a C++ API on top of the C API.

Would this still require reimplementing the Rust sources in C++? This is probably out of my comfort zone.

> This library is written in Rust, and I'm migrating its dependencies from C to pure Rust, so eventually I may be able to completely remove _C_ as a dependency, but Rust is here to stay. I'm not planning to use C++.

Does this mean that if I went with the approach below, it would eventually not be an option? Or will the "The static libraries produced by Rust are compatible with GCC/Clang and MSVC and can be linked directly with a C linker" part still apply?

Sorry for all of the questions - I know literally nothing about Rust.
 
> Maybe you could pre-compile this library and keep the precompiled binaries around, instead of building them from scratch each time? The static libraries produced by Rust are compatible with GCC/Clang and MSVC and can be linked directly with a C linker.

Hmmm, that could be an option. Thanks. :)

**Comment by kornelski** [comment]
> Would this still require reimplementing the Rust sources in C++?

No. C++ can use the existing C API, so you can write an idiomatic C++ API on top of the C API.

> Does this mean that if I went with the approach below, it would eventually not be an option?

Rust can export a C API, and this won't change (Rust can "prentend" to be C, so even a 100% pure Rust program can be used from C, C++ and other languages that understand C APIs).
